export const listData = [
  {
    id: 1,
    title: "Cozy Apartment Overlooking Swansea Bay",
    images: [
      "https://images.pexels.com/photos/276671/pexels-photo-276671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 2,
    bathroom: 1,
    price: 1200,
    address: "10 Mumbles Road, Swansea",
    latitude: 51.5771,
    longitude: -3.9875,
  },
  {
    id: 2,
    title: "Modern Flat in City Centre",
    images: [
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 1,
    bathroom: 1,
    price: 900,
    address: "22 High Street, Swansea",
    latitude: 51.6225,
    longitude: -3.9416,
  },
  {
    id: 3,
    title: "Spacious Family Home near Clyne Gardens",
    images: [
      "https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 4,
    bathroom: 2,
    price: 1800,
    address: "15 Clyne Crescent, Swansea",
    latitude: 51.6031,
    longitude: -4.0028,
  },
  {
    id: 4,
    title: "Luxury Apartment in SA1 Waterfront",
    images: [
      "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 2,
    bathroom: 2,
    price: 1500,
    address: "32 Trawler Road, Swansea Marina",
    latitude: 51.6168,
    longitude: -3.9353,
  },
  {
    id: 5,
    title: "Quaint Cottage in Mumbles",
    images: [
      "https://images.pexels.com/photos/259602/pexels-photo-259602.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 3,
    bathroom: 1,
    price: 1100,
    address: "5 Newton Road, Mumbles",
    latitude: 51.5748,
    longitude: -4.0004,
  },
  {
    id: 6,
    title: "Modern House Near Singleton Park",
    images: [
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 1400,
    address: "20 Brynmill Lane, Swansea",
    latitude: 51.6136,
    longitude: -3.9798,
  },
  {
    id: 7,
    title: "Compact Studio in Uplands",
    images: [
      "https://images.pexels.com/photos/706137/pexels-photo-706137.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 1,
    bathroom: 1,
    price: 750,
    address: "45 Uplands Crescent, Swansea",
    latitude: 51.6182,
    longitude: -3.9756,
  },
  {
    id: 8,
    title: "Beautiful Seafront Property in Langland",
    images: [
      "https://images.pexels.com/photos/462235/pexels-photo-462235.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 5,
    bathroom: 3,
    price: 2200,
    address: "8 Langland Bay Road, Swansea",
    latitude: 51.5755,
    longitude: -4.0079,
  },
  {
    id: 9,
    title: "Charming Townhouse Near Castle Square",
    images: [
      "https://images.pexels.com/photos/3958962/pexels-photo-3958962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 3,
    bathroom: 2,
    price: 1300,
    address: "12 Castle Street, Swansea",
    latitude: 51.6206,
    longitude: -3.9427,
  },
  {
    id: 10,
    title: "Stylish Penthouse in Meridian Quay",
    images: [
      "https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    bedroom: 3,
    bathroom: 3,
    price: 2500,
    address: "28 Meridian Tower, Swansea",
    latitude: 51.6163,
    longitude: -3.936,
  },
];

export const detailPropertyData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 51.6168,
  longitude: -3.9353,
  city: "Swansea",
  address: "1234 Beachside Lane, Swansea",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Nestled near the beautiful Swansea Bay, this cozy apartment is perfect for those seeking comfort and convenience. It features two spacious bedrooms, a modern bathroom, and a sleek open-plan living area. Situated close to schools, public transport, and restaurants, this home offers both practicality and charm. Enjoy the serene views and vibrant local lifestyle in this delightful property.",
};

export const userData = {
  id: 1,
  name: "vineeth",
  images:
    "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};

// export const propertyList = [
//   {
//     postData: {
//       title: "Modern Apartment in City Center",
//       price: 900,
//       images: [
//         "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
//         "https://images.pexels.com/photos/37347/office-sunset-dusk-building.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
//       ],
//       address: "22 High Street, Swansea",
//       city: "Uplands",
//       property: "apartment",
//       bedroom: 1,
//       bathroom: 1,
//       type: "rent",
//       latitude: "51.6225",
//       longitude: "-3.9416",
//     },
//     postDetail: {
//       desc: "des1",
//       utilities: "Owner responsible",
//       pet: "Not Allowed",
//       income: "3x income",
//       size: 88,
//       school: 100,
//       bus: 20,
//       train: 150,
//     },
//   },
//   {
//     postData: {
//       title: "Spacious House Near Beach",
//       price: 1500,
//       images: [
//         "https://images.pexels.com/photos/1643388/pexels-photo-1643388.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
//       ],
//       address: "45 Bay View Road, Swansea",
//       city: "Mumbles",
//       property: "house",
//       bedroom: 3,
//       bathroom: 2,
//       type: "rent",
//       latitude: "51.5738",
//       longitude: "-4.0011",
//     },
//     postDetail: {
//       desc: "des2",
//       utilities: "Tenant responsible",
//       pet: "Allowed",
//       income: "3x income",
//       size: 180,
//       school: 150,
//       bus: 30,
//       train: 200,
//     },
//   },
//   {
//     postData: {
//       title: "Cozy Studio Apartment",
//       price: 700,
//       images: [
//         "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
//       ],
//       address: "10 Kingsway, Swansea",
//       city: "City Centre",
//       property: "studio",
//       bedroom: 0,
//       bathroom: 1,
//       type: "rent",
//       latitude: "51.6194",
//       longitude: "-3.9449",
//     },
//     postDetail: {
//       desc: "des3",
//       utilities: "Owner responsible",
//       pet: "Not Allowed",
//       income: "3x income",
//       size: 45,
//       school: 80,
//       bus: 10,
//       train: 100,
//     },
//   },
// ];
